### ISSUE TITLE
Mana symbols

### ISSUE THREAD

**Issue by rhblind** [Saeris/react-keyrune#2]
Hello, thanks for the great work you've done with both the CSS icons and the React wrapper.
I have a little feature request, namely mana symbols. Would've been great if that's possible to add!

**Comment by Saeris** [comment]
Hey! I'm glad you like the component! As for your question, there is a separate component for Mana symbols which you can find here:

https://github.com/Saeris/react-mana

I'm not the author of the CSS / Icon Fonts and don't personally add new symbols. Those come to you courtesy of the maintainers of the required peer dependencies for each component, links to which can be found in the acknowledgements section of the readme. There are two separate components specifically to pair with the two separate icon fonts and I do not plan to combine the two.

**Comment by rhblind** [comment]
Oh alright!
Thanks anyways 😊
